// Code generated by goctl. DO NOT EDIT.
// Source: mooon-mailbox.proto

package mooonmailbox

import (
	"context"

	"mooon-mailbox/pb/mooon-mailbox"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteLetterReq    = mooon_mailbox.DeleteLetterReq
	DeleteLetterResp   = mooon_mailbox.DeleteLetterResp
	DeliverMessageReq  = mooon_mailbox.DeliverMessageReq
	DeliverMessageResp = mooon_mailbox.DeliverMessageResp
	Letter             = mooon_mailbox.Letter
	ListMessagesReq    = mooon_mailbox.ListMessagesReq
	ListMessagesResp   = mooon_mailbox.ListMessagesResp
	MarkAsReadReq      = mooon_mailbox.MarkAsReadReq
	MarkAsReadResp     = mooon_mailbox.MarkAsReadResp

	MooonMailbox interface {
		DeliverMessage(ctx context.Context, in *DeliverMessageReq, opts ...grpc.CallOption) (*DeliverMessageResp, error)
		ListMessages(ctx context.Context, in *ListMessagesReq, opts ...grpc.CallOption) (*ListMessagesResp, error)
		MarkAsRead(ctx context.Context, in *MarkAsReadReq, opts ...grpc.CallOption) (*MarkAsReadResp, error)
		DeleteLetter(ctx context.Context, in *DeleteLetterReq, opts ...grpc.CallOption) (*DeleteLetterResp, error)
	}

	defaultMooonMailbox struct {
		cli zrpc.Client
	}
)

func NewMooonMailbox(cli zrpc.Client) MooonMailbox {
	return &defaultMooonMailbox{
		cli: cli,
	}
}

func (m *defaultMooonMailbox) DeliverMessage(ctx context.Context, in *DeliverMessageReq, opts ...grpc.CallOption) (*DeliverMessageResp, error) {
	client := mooon_mailbox.NewMooonMailboxClient(m.cli.Conn())
	return client.DeliverMessage(ctx, in, opts...)
}

func (m *defaultMooonMailbox) ListMessages(ctx context.Context, in *ListMessagesReq, opts ...grpc.CallOption) (*ListMessagesResp, error) {
	client := mooon_mailbox.NewMooonMailboxClient(m.cli.Conn())
	return client.ListMessages(ctx, in, opts...)
}

func (m *defaultMooonMailbox) MarkAsRead(ctx context.Context, in *MarkAsReadReq, opts ...grpc.CallOption) (*MarkAsReadResp, error) {
	client := mooon_mailbox.NewMooonMailboxClient(m.cli.Conn())
	return client.MarkAsRead(ctx, in, opts...)
}

func (m *defaultMooonMailbox) DeleteLetter(ctx context.Context, in *DeleteLetterReq, opts ...grpc.CallOption) (*DeleteLetterResp, error) {
	client := mooon_mailbox.NewMooonMailboxClient(m.cli.Conn())
	return client.DeleteLetter(ctx, in, opts...)
}
