// Code generated by goctl. DO NOT EDIT.
// Source: mooon-mailbox.proto

package mooonmailbox

import (
	"context"

	"mooon-mailbox/pb/mooon-mailbox"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteMessageReq   = mooon_mailbox.DeleteMessageReq
	DeleteMessageResp  = mooon_mailbox.DeleteMessageResp
	DeliverMessageReq  = mooon_mailbox.DeliverMessageReq
	DeliverMessageResp = mooon_mailbox.DeliverMessageResp
	Letter             = mooon_mailbox.Letter
	ListMessagesReq    = mooon_mailbox.ListMessagesReq
	ListMessagesResp   = mooon_mailbox.ListMessagesResp
	MarkAsReadReq      = mooon_mailbox.MarkAsReadReq
	MarkAsReadResp     = mooon_mailbox.MarkAsReadResp

	MooonMailbox interface {
		DeliverMessage(ctx context.Context, in *DeliverMessageReq, opts ...grpc.CallOption) (*DeliverMessageResp, error)
		ListMessages(ctx context.Context, in *ListMessagesReq, opts ...grpc.CallOption) (*ListMessagesResp, error)
		MarkMessageAsRead(ctx context.Context, in *MarkAsReadReq, opts ...grpc.CallOption) (*MarkAsReadResp, error)
		DeleteMessages(ctx context.Context, in *DeleteMessageReq, opts ...grpc.CallOption) (*DeleteMessageResp, error)
	}

	defaultMooonMailbox struct {
		cli zrpc.Client
	}
)

func NewMooonMailbox(cli zrpc.Client) MooonMailbox {
	return &defaultMooonMailbox{
		cli: cli,
	}
}

func (m *defaultMooonMailbox) DeliverMessage(ctx context.Context, in *DeliverMessageReq, opts ...grpc.CallOption) (*DeliverMessageResp, error) {
	client := mooon_mailbox.NewMooonMailboxClient(m.cli.Conn())
	return client.DeliverMessage(ctx, in, opts...)
}

func (m *defaultMooonMailbox) ListMessages(ctx context.Context, in *ListMessagesReq, opts ...grpc.CallOption) (*ListMessagesResp, error) {
	client := mooon_mailbox.NewMooonMailboxClient(m.cli.Conn())
	return client.ListMessages(ctx, in, opts...)
}

func (m *defaultMooonMailbox) MarkMessageAsRead(ctx context.Context, in *MarkAsReadReq, opts ...grpc.CallOption) (*MarkAsReadResp, error) {
	client := mooon_mailbox.NewMooonMailboxClient(m.cli.Conn())
	return client.MarkMessageAsRead(ctx, in, opts...)
}

func (m *defaultMooonMailbox) DeleteMessages(ctx context.Context, in *DeleteMessageReq, opts ...grpc.CallOption) (*DeleteMessageResp, error) {
	client := mooon_mailbox.NewMooonMailboxClient(m.cli.Conn())
	return client.DeleteMessages(ctx, in, opts...)
}
