// Code generated by goctl. DO NOT EDIT.
// Source: mooon-mailbox.proto

package server

import (
	"context"

	"mooon-mailbox/internal/logic"
	"mooon-mailbox/internal/svc"
	"mooon-mailbox/pb/mooon-mailbox"
)

type MooonMailboxServer struct {
	svcCtx *svc.ServiceContext
	mooon_mailbox.UnimplementedMooonMailboxServer
}

func NewMooonMailboxServer(svcCtx *svc.ServiceContext) *MooonMailboxServer {
	return &MooonMailboxServer{
		svcCtx: svcCtx,
	}
}

func (s *MooonMailboxServer) DeliverMessage(ctx context.Context, in *mooon_mailbox.DeliverMessageReq) (*mooon_mailbox.DeliverMessageResp, error) {
	l := logic.NewDeliverMessageLogic(ctx, s.svcCtx)
	return l.DeliverMessage(in)
}

func (s *MooonMailboxServer) ListMessages(ctx context.Context, in *mooon_mailbox.ListMessagesReq) (*mooon_mailbox.ListMessagesResp, error) {
	l := logic.NewListMessagesLogic(ctx, s.svcCtx)
	return l.ListMessages(in)
}

func (s *MooonMailboxServer) MarkAsRead(ctx context.Context, in *mooon_mailbox.MarkAsReadReq) (*mooon_mailbox.MarkAsReadResp, error) {
	l := logic.NewMarkAsReadLogic(ctx, s.svcCtx)
	return l.MarkAsRead(in)
}

func (s *MooonMailboxServer) DeleteLetter(ctx context.Context, in *mooon_mailbox.DeleteLetterReq) (*mooon_mailbox.DeleteLetterResp, error) {
	l := logic.NewDeleteLetterLogic(ctx, s.svcCtx)
	return l.DeleteLetter(in)
}
