// Written by yijian on 2024/01/20

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.19.4
// source: mooon-mailbox.proto

package mooon_mailbox

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListMessagesReq_ListAction int32

const (
	ListMessagesReq_LA_ALL         ListMessagesReq_ListAction = 0 // 所有信件
	ListMessagesReq_LA_ONLY_UNREAD ListMessagesReq_ListAction = 1 // 仅未读信件
	ListMessagesReq_LA_ONLY_READ   ListMessagesReq_ListAction = 2 // 仅已读信件
)

// Enum value maps for ListMessagesReq_ListAction.
var (
	ListMessagesReq_ListAction_name = map[int32]string{
		0: "LA_ALL",
		1: "LA_ONLY_UNREAD",
		2: "LA_ONLY_READ",
	}
	ListMessagesReq_ListAction_value = map[string]int32{
		"LA_ALL":         0,
		"LA_ONLY_UNREAD": 1,
		"LA_ONLY_READ":   2,
	}
)

func (x ListMessagesReq_ListAction) Enum() *ListMessagesReq_ListAction {
	p := new(ListMessagesReq_ListAction)
	*p = x
	return p
}

func (x ListMessagesReq_ListAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListMessagesReq_ListAction) Descriptor() protoreflect.EnumDescriptor {
	return file_mooon_mailbox_proto_enumTypes[0].Descriptor()
}

func (ListMessagesReq_ListAction) Type() protoreflect.EnumType {
	return &file_mooon_mailbox_proto_enumTypes[0]
}

func (x ListMessagesReq_ListAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListMessagesReq_ListAction.Descriptor instead.
func (ListMessagesReq_ListAction) EnumDescriptor() ([]byte, []int) {
	return file_mooon_mailbox_proto_rawDescGZIP(), []int{3, 0}
}

// 信件
type Letter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LetterId    string `protobuf:"bytes,1,opt,name=letter_id,json=letterId,proto3" json:"letter_id,omitempty"`           // 信件 ID
	LetterBody  string `protobuf:"bytes,2,opt,name=letter_body,json=letterBody,proto3" json:"letter_body,omitempty"`     // 信件内容
	DeliverTime int64  `protobuf:"varint,3,opt,name=deliver_time,json=deliverTime,proto3" json:"deliver_time,omitempty"` // 投递时间
	ArrivalTime int64  `protobuf:"varint,4,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"` // 到达时间
}

func (x *Letter) Reset() {
	*x = Letter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mooon_mailbox_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Letter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Letter) ProtoMessage() {}

func (x *Letter) ProtoReflect() protoreflect.Message {
	mi := &file_mooon_mailbox_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Letter.ProtoReflect.Descriptor instead.
func (*Letter) Descriptor() ([]byte, []int) {
	return file_mooon_mailbox_proto_rawDescGZIP(), []int{0}
}

func (x *Letter) GetLetterId() string {
	if x != nil {
		return x.LetterId
	}
	return ""
}

func (x *Letter) GetLetterBody() string {
	if x != nil {
		return x.LetterBody
	}
	return ""
}

func (x *Letter) GetDeliverTime() int64 {
	if x != nil {
		return x.DeliverTime
	}
	return 0
}

func (x *Letter) GetArrivalTime() int64 {
	if x != nil {
		return x.ArrivalTime
	}
	return 0
}

// 投递消息
type DeliverMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipient  string `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`                     // 收件人
	LetterBody string `protobuf:"bytes,2,opt,name=letter_body,json=letterBody,proto3" json:"letter_body,omitempty"` // 信件内容
}

func (x *DeliverMessageReq) Reset() {
	*x = DeliverMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mooon_mailbox_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliverMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverMessageReq) ProtoMessage() {}

func (x *DeliverMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_mooon_mailbox_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverMessageReq.ProtoReflect.Descriptor instead.
func (*DeliverMessageReq) Descriptor() ([]byte, []int) {
	return file_mooon_mailbox_proto_rawDescGZIP(), []int{1}
}

func (x *DeliverMessageReq) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *DeliverMessageReq) GetLetterBody() string {
	if x != nil {
		return x.LetterBody
	}
	return ""
}

type DeliverMessageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipient string `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"` // 收件人
}

func (x *DeliverMessageResp) Reset() {
	*x = DeliverMessageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mooon_mailbox_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliverMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverMessageResp) ProtoMessage() {}

func (x *DeliverMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_mooon_mailbox_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverMessageResp.ProtoReflect.Descriptor instead.
func (*DeliverMessageResp) Descriptor() ([]byte, []int) {
	return file_mooon_mailbox_proto_rawDescGZIP(), []int{2}
}

func (x *DeliverMessageResp) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

// 列出信件
type ListMessagesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipient  string                     `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`                                                                    // 收件人
	PageStart  uint32                     `protobuf:"varint,2,opt,name=page_start,json=pageStart,proto3" json:"page_start,omitempty"`                                                  // 起始页，值为空表示首页
	PageSize   uint32                     `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                                                     // 页大小，默认为 10
	ListAction ListMessagesReq_ListAction `protobuf:"varint,4,opt,name=list_action,json=listAction,proto3,enum=mooon_mailbox.ListMessagesReq_ListAction" json:"list_action,omitempty"` // 列出动作
}

func (x *ListMessagesReq) Reset() {
	*x = ListMessagesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mooon_mailbox_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesReq) ProtoMessage() {}

func (x *ListMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_mooon_mailbox_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesReq.ProtoReflect.Descriptor instead.
func (*ListMessagesReq) Descriptor() ([]byte, []int) {
	return file_mooon_mailbox_proto_rawDescGZIP(), []int{3}
}

func (x *ListMessagesReq) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *ListMessagesReq) GetPageStart() uint32 {
	if x != nil {
		return x.PageStart
	}
	return 0
}

func (x *ListMessagesReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMessagesReq) GetListAction() ListMessagesReq_ListAction {
	if x != nil {
		return x.ListAction
	}
	return ListMessagesReq_LA_ALL
}

type ListMessagesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipient string    `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"` // 收件人ListAction
	Letters   []*Letter `protobuf:"bytes,2,rep,name=letters,proto3" json:"letters,omitempty"`     // 信件列表
}

func (x *ListMessagesResp) Reset() {
	*x = ListMessagesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mooon_mailbox_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMessagesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResp) ProtoMessage() {}

func (x *ListMessagesResp) ProtoReflect() protoreflect.Message {
	mi := &file_mooon_mailbox_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResp.ProtoReflect.Descriptor instead.
func (*ListMessagesResp) Descriptor() ([]byte, []int) {
	return file_mooon_mailbox_proto_rawDescGZIP(), []int{4}
}

func (x *ListMessagesResp) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *ListMessagesResp) GetLetters() []*Letter {
	if x != nil {
		return x.Letters
	}
	return nil
}

// 标记为已读
type MarkAsReadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipient    string   `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`                             // 收件人
	LetterIdList []string `protobuf:"bytes,2,rep,name=letter_id_list,json=letterIdList,proto3" json:"letter_id_list,omitempty"` // 信件 ID
}

func (x *MarkAsReadReq) Reset() {
	*x = MarkAsReadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mooon_mailbox_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkAsReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadReq) ProtoMessage() {}

func (x *MarkAsReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_mooon_mailbox_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadReq.ProtoReflect.Descriptor instead.
func (*MarkAsReadReq) Descriptor() ([]byte, []int) {
	return file_mooon_mailbox_proto_rawDescGZIP(), []int{5}
}

func (x *MarkAsReadReq) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *MarkAsReadReq) GetLetterIdList() []string {
	if x != nil {
		return x.LetterIdList
	}
	return nil
}

type MarkAsReadResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipient string `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"` // 收件人
}

func (x *MarkAsReadResp) Reset() {
	*x = MarkAsReadResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mooon_mailbox_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkAsReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadResp) ProtoMessage() {}

func (x *MarkAsReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_mooon_mailbox_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadResp.ProtoReflect.Descriptor instead.
func (*MarkAsReadResp) Descriptor() ([]byte, []int) {
	return file_mooon_mailbox_proto_rawDescGZIP(), []int{6}
}

func (x *MarkAsReadResp) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

// 删除信件
type DeleteLetterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipient    string   `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`                             // 收件人
	LetterIdList []string `protobuf:"bytes,2,rep,name=letter_id_list,json=letterIdList,proto3" json:"letter_id_list,omitempty"` // 信件 ID
}

func (x *DeleteLetterReq) Reset() {
	*x = DeleteLetterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mooon_mailbox_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLetterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLetterReq) ProtoMessage() {}

func (x *DeleteLetterReq) ProtoReflect() protoreflect.Message {
	mi := &file_mooon_mailbox_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLetterReq.ProtoReflect.Descriptor instead.
func (*DeleteLetterReq) Descriptor() ([]byte, []int) {
	return file_mooon_mailbox_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLetterReq) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *DeleteLetterReq) GetLetterIdList() []string {
	if x != nil {
		return x.LetterIdList
	}
	return nil
}

type DeleteLetterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipient string `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"` // 收件人
}

func (x *DeleteLetterResp) Reset() {
	*x = DeleteLetterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mooon_mailbox_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLetterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLetterResp) ProtoMessage() {}

func (x *DeleteLetterResp) ProtoReflect() protoreflect.Message {
	mi := &file_mooon_mailbox_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLetterResp.ProtoReflect.Descriptor instead.
func (*DeleteLetterResp) Descriptor() ([]byte, []int) {
	return file_mooon_mailbox_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteLetterResp) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

var File_mooon_mailbox_proto protoreflect.FileDescriptor

var file_mooon_mailbox_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x6f, 0x6f, 0x6f, 0x6e, 0x2d, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6d, 0x6f, 0x6f, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x69,
	0x6c, 0x62, 0x6f, 0x78, 0x22, 0x8c, 0x01, 0x0a, 0x06, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12,
	0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x21, 0x0a,
	0x0c, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x52, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63,
	0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72,
	0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x65, 0x74,
	0x74, 0x65, 0x72, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x32, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a,
	0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x22, 0xf7, 0x01, 0x0a, 0x0f,
	0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x6c, 0x69, 0x73,
	0x74, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29,
	0x2e, 0x6d, 0x6f, 0x6f, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3e, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x41, 0x5f, 0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12,
	0x12, 0x0a, 0x0e, 0x4c, 0x41, 0x5f, 0x4f, 0x4e, 0x4c, 0x59, 0x5f, 0x55, 0x4e, 0x52, 0x45, 0x41,
	0x44, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4c, 0x41, 0x5f, 0x4f, 0x4e, 0x4c, 0x59, 0x5f, 0x52,
	0x45, 0x41, 0x44, 0x10, 0x02, 0x22, 0x61, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63,
	0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x07, 0x6c, 0x65, 0x74, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x6f, 0x6f, 0x6f, 0x6e,
	0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x2e, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x52,
	0x07, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x73, 0x22, 0x53, 0x0a, 0x0d, 0x4d, 0x61, 0x72, 0x6b,
	0x41, 0x73, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63,
	0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x6c, 0x65, 0x74, 0x74, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0c, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2e, 0x0a,
	0x0e, 0x4d, 0x61, 0x72, 0x6b, 0x41, 0x73, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x55, 0x0a,
	0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x24,
	0x0a, 0x0e, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x49, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x30, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65,
	0x74, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63,
	0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x32, 0xd7, 0x02, 0x0a, 0x0c, 0x4d, 0x6f, 0x6f, 0x6f, 0x6e,
	0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x12, 0x56, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x2e, 0x6d, 0x6f, 0x6f,
	0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x6d,
	0x6f, 0x6f, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x2e, 0x44, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x50, 0x0a, 0x0d, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x1e, 0x2e, 0x6d, 0x6f, 0x6f, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x1f, 0x2e, 0x6d, 0x6f, 0x6f, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x4b, 0x0a, 0x0c, 0x6d, 0x61, 0x72, 0x6b, 0x5f, 0x61, 0x73, 0x5f, 0x72, 0x65, 0x61,
	0x64, 0x12, 0x1c, 0x2e, 0x6d, 0x6f, 0x6f, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f,
	0x78, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x41, 0x73, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x1a,
	0x1d, 0x2e, 0x6d, 0x6f, 0x6f, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x2e,
	0x4d, 0x61, 0x72, 0x6b, 0x41, 0x73, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x50,
	0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12,
	0x1e, 0x2e, 0x6d, 0x6f, 0x6f, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x1f, 0x2e, 0x6d, 0x6f, 0x6f, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x6d, 0x6f, 0x6f, 0x6f, 0x6e, 0x2d, 0x6d, 0x61, 0x69, 0x6c,
	0x62, 0x6f, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mooon_mailbox_proto_rawDescOnce sync.Once
	file_mooon_mailbox_proto_rawDescData = file_mooon_mailbox_proto_rawDesc
)

func file_mooon_mailbox_proto_rawDescGZIP() []byte {
	file_mooon_mailbox_proto_rawDescOnce.Do(func() {
		file_mooon_mailbox_proto_rawDescData = protoimpl.X.CompressGZIP(file_mooon_mailbox_proto_rawDescData)
	})
	return file_mooon_mailbox_proto_rawDescData
}

var file_mooon_mailbox_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mooon_mailbox_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mooon_mailbox_proto_goTypes = []interface{}{
	(ListMessagesReq_ListAction)(0), // 0: mooon_mailbox.ListMessagesReq.ListAction
	(*Letter)(nil),                  // 1: mooon_mailbox.Letter
	(*DeliverMessageReq)(nil),       // 2: mooon_mailbox.DeliverMessageReq
	(*DeliverMessageResp)(nil),      // 3: mooon_mailbox.DeliverMessageResp
	(*ListMessagesReq)(nil),         // 4: mooon_mailbox.ListMessagesReq
	(*ListMessagesResp)(nil),        // 5: mooon_mailbox.ListMessagesResp
	(*MarkAsReadReq)(nil),           // 6: mooon_mailbox.MarkAsReadReq
	(*MarkAsReadResp)(nil),          // 7: mooon_mailbox.MarkAsReadResp
	(*DeleteLetterReq)(nil),         // 8: mooon_mailbox.DeleteLetterReq
	(*DeleteLetterResp)(nil),        // 9: mooon_mailbox.DeleteLetterResp
}
var file_mooon_mailbox_proto_depIdxs = []int32{
	0, // 0: mooon_mailbox.ListMessagesReq.list_action:type_name -> mooon_mailbox.ListMessagesReq.ListAction
	1, // 1: mooon_mailbox.ListMessagesResp.letters:type_name -> mooon_mailbox.Letter
	2, // 2: mooon_mailbox.MooonMailbox.deliver_message:input_type -> mooon_mailbox.DeliverMessageReq
	4, // 3: mooon_mailbox.MooonMailbox.list_messages:input_type -> mooon_mailbox.ListMessagesReq
	6, // 4: mooon_mailbox.MooonMailbox.mark_as_read:input_type -> mooon_mailbox.MarkAsReadReq
	8, // 5: mooon_mailbox.MooonMailbox.delete_letter:input_type -> mooon_mailbox.DeleteLetterReq
	3, // 6: mooon_mailbox.MooonMailbox.deliver_message:output_type -> mooon_mailbox.DeliverMessageResp
	5, // 7: mooon_mailbox.MooonMailbox.list_messages:output_type -> mooon_mailbox.ListMessagesResp
	7, // 8: mooon_mailbox.MooonMailbox.mark_as_read:output_type -> mooon_mailbox.MarkAsReadResp
	9, // 9: mooon_mailbox.MooonMailbox.delete_letter:output_type -> mooon_mailbox.DeleteLetterResp
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mooon_mailbox_proto_init() }
func file_mooon_mailbox_proto_init() {
	if File_mooon_mailbox_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mooon_mailbox_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Letter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mooon_mailbox_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliverMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mooon_mailbox_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliverMessageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mooon_mailbox_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMessagesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mooon_mailbox_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMessagesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mooon_mailbox_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkAsReadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mooon_mailbox_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkAsReadResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mooon_mailbox_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLetterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mooon_mailbox_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLetterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mooon_mailbox_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mooon_mailbox_proto_goTypes,
		DependencyIndexes: file_mooon_mailbox_proto_depIdxs,
		EnumInfos:         file_mooon_mailbox_proto_enumTypes,
		MessageInfos:      file_mooon_mailbox_proto_msgTypes,
	}.Build()
	File_mooon_mailbox_proto = out.File
	file_mooon_mailbox_proto_rawDesc = nil
	file_mooon_mailbox_proto_goTypes = nil
	file_mooon_mailbox_proto_depIdxs = nil
}
